language: node_js
node_js:
  - "10.7.0"

jobs:
  include:
  - stage: Produce Coverage
    node_js: "10.7.0"
    script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

